# Visualização de dados

## Aula 1 - Tratamento, exploração e visualização de dados

## 1. Tratamento, exploração e visualização de dados

In [79]:
import pandas as pd

In [92]:
ibge_estimativa_git = pd.read_excel(r"https://github.com/alura-cursos/agendamento-hospitalar/blob/main/dados/estimativa_dou_2020.xls?raw=true")

In [93]:
ibge_estimativa_git.head()

,ESTIMATIVAS DA POPULAÇÃO RESIDENTE NO BRASIL E UNIDADES DA FEDERAÇÃO COM DATA DE REFERÊNCIA EM 1º DE JULHO DE 2020,Unnamed: 1,Unnamed: 2
0,BRASIL E UNIDADES DA FEDERAÇÃO,NaN,POPULAÇÃO ESTIMADA
1,Brasil,NaN,211755692
2,Região Norte,NaN,18672591
3,Rondônia,NaN,1796460
4,Acre,NaN,894470

In [94]:
dados_da_populacao_io = """
Posição	Unidade federativa	População	% da pop. Total	País comparável
Habitantes
1	São Paulo	46 649 132	21,9%	Flag of Spain.svg Espanha (46 439 864)
2	Minas Gerais	21 411 923	10,1%	Sri Lanka (20 675 000)
3	Rio de Janeiro	17 463 349	8,2%	Países Baixos (16 922 900)
4	Bahia Bahia	14 985 284	7,1%	Chade (14 037 000)
5	Paraná	11 597 484	5,4%	Bolívia (11 410 651)
6	Rio Grande do Sul	11 466 630	5,4%	Bélgica (11 250 659)
7	Pernambuco	9 674 793	4,5%	Bielorrússia (9 485 300)
8	Ceará	9 240 580	4,3%	Emirados Árabes Unidos (9 157 000)
9	Pará	8 777 124	4,1%	Áustria (8 602 112)
10	Santa Catarina	7 338 473	3,4%	Sérvia (7 114 393)
11	Goiás	7 206 589	3,4%	Paraguai (7 003 406)
12	Maranhão	7 153 262	3,4%	Paraguai (7 003 406)
13	Amazonas	4 269 995	2,0%	Líbano (4 168 000)
14	Espírito Santo	4 108 508	1,9%	Líbano (4 168 000)
15	Paraíba	4 059 905	1,9%	Líbano (4 168 000)
16	Mato Grosso	3 567 234	1,7%	Uruguai (3 415 866)
17	Rio Grande do Norte	3 560 903	1,7%	Uruguai (3 415 866)
18	Alagoas	3 365 351	1,6%	Uruguai (3 415 866)
19	Piauí	3 289 290	1,6%	Kuwait (3 268 431)
20	Distrito Federal	3 094 325	1,4%	Lituânia (2 900 787)
21	Mato Grosso do Sul	2 839 188	1,3%	Jamaica (2 717 991)
22	Sergipe	2 338 474	1,1%	Namíbia (2 280 700)
23	Rondônia	1 815 278	0,8%	Gabão (1 725 000)
24	Tocantins	1 607 363	0,7%	Bahrein (1 359 800)
25	Acre	906 876	0,4%	Fiji (859 178)
26	Amapá	877 613	0,4%	Fiji (859 178)
27	Roraima	652 713	0,3%	Luxemburgo (562 958)"""

In [95]:
from io import StringIO  

dados_da_populacao_io = StringIO(dados_da_populacao_io)

dados_da_populacao_io = pd.read_csv(dados_da_populacao_io, sep = "\t")

dados_da_populacao_io

,Posição,Unidade federativa,População,% da pop. Total,País comparável
0,Habitantes,NaN,NaN,NaN,NaN
1,1,São Paulo,46 649 132,"21,9%",Flag of Spain.svg Espanha (46 439 864)
2,2,Minas Gerais,21 411 923,"10,1%",Sri Lanka (20 675 000)
3,3,Rio de Janeiro,17 463 349,"8,2%",Países Baixos (16 922 900)
4,4,Bahia Bahia,14 985 284,"7,1%",Chade (14 037 000)
5,5,Paraná,11 597 484,"5,4%",Bolívia (11 410 651)
6,6,Rio Grande do Sul,11 466 630,"5,4%",Bélgica (11 250 659)
7,7,Pernambuco,9 674 793,"4,5%",Bielorrússia (9 485 300)
8,8,Ceará,9 240 580,"4,3%",Emirados Árabes Unidos (9 157 000)
9,9,Pará,8 777 124,"4,1%",Áustria (8 602 112)
10,10,Santa Catarina,7 338 473,"3,4%",Sérvia (7 114 393)
11,11,Goiás,7 206 589,"3,4%",Paraguai (7 003 406)
12,12,Maranhão,7 153 262,"3,4%",Paraguai (7 003 406)
13,13,Amazonas,4 269 995,"2,0%",Líbano (4 168 000)
14,14,Espírito Santo,4 108 508,"1,9%",Líbano (4 168 000)
15,15,Paraíba,4 059 905,"1,9%",Líbano (4 168 000)
16,16,Mato Grosso,3 567 234,"1,7%",Uruguai (3 415 866)
17,17,Rio Grande do Norte,3 560 903,"1,7%",Uruguai (3 415 866)
18,18,Alagoas,3 365 351,"1,6%",Uruguai (3 415 866)
19,19,Piauí,3 289 290,"1,6%",Kuwait (3 268 431)
20,20,Distrito Federal,3 094 325,"1,4%",Lituânia (2 900 787)
21,21,Mato Grosso do Sul,2 839 188,"1,3%",Jamaica (2 717 991)
22,22,Sergipe,2 338 474,"1,1%",Namíbia (2 280 700)
23,23,Rondônia,1 815 278,"0,8%",Gabão (1 725 000)
24,24,Tocantins,1 607 363,"0,7%",Bahrein (1 359 800)
25,25,Acre,906 876,"0,4%",Fiji (859 178)
26,26,Amapá,877 613,"0,4%",Fiji (859 178)
27,27,Roraima,652 713,"0,3%",Luxemburgo (562 958)

## Removendo valores nulos

In [96]:
dados_da_populacao_io = dados_da_populacao_io.dropna()

dados_da_populacao_io

,Posição,Unidade federativa,População,% da pop. Total,País comparável
1,1,São Paulo,46 649 132,"21,9%",Flag of Spain.svg Espanha (46 439 864)
2,2,Minas Gerais,21 411 923,"10,1%",Sri Lanka (20 675 000)
3,3,Rio de Janeiro,17 463 349,"8,2%",Países Baixos (16 922 900)
4,4,Bahia Bahia,14 985 284,"7,1%",Chade (14 037 000)
5,5,Paraná,11 597 484,"5,4%",Bolívia (11 410 651)
6,6,Rio Grande do Sul,11 466 630,"5,4%",Bélgica (11 250 659)
7,7,Pernambuco,9 674 793,"4,5%",Bielorrússia (9 485 300)
8,8,Ceará,9 240 580,"4,3%",Emirados Árabes Unidos (9 157 000)
9,9,Pará,8 777 124,"4,1%",Áustria (8 602 112)
10,10,Santa Catarina,7 338 473,"3,4%",Sérvia (7 114 393)
11,11,Goiás,7 206 589,"3,4%",Paraguai (7 003 406)
12,12,Maranhão,7 153 262,"3,4%",Paraguai (7 003 406)
13,13,Amazonas,4 269 995,"2,0%",Líbano (4 168 000)
14,14,Espírito Santo,4 108 508,"1,9%",Líbano (4 168 000)
15,15,Paraíba,4 059 905,"1,9%",Líbano (4 168 000)
16,16,Mato Grosso,3 567 234,"1,7%",Uruguai (3 415 866)
17,17,Rio Grande do Norte,3 560 903,"1,7%",Uruguai (3 415 866)
18,18,Alagoas,3 365 351,"1,6%",Uruguai (3 415 866)
19,19,Piauí,3 289 290,"1,6%",Kuwait (3 268 431)
20,20,Distrito Federal,3 094 325,"1,4%",Lituânia (2 900 787)
21,21,Mato Grosso do Sul,2 839 188,"1,3%",Jamaica (2 717 991)
22,22,Sergipe,2 338 474,"1,1%",Namíbia (2 280 700)
23,23,Rondônia,1 815 278,"0,8%",Gabão (1 725 000)
24,24,Tocantins,1 607 363,"0,7%",Bahrein (1 359 800)
25,25,Acre,906 876,"0,4%",Fiji (859 178)
26,26,Amapá,877 613,"0,4%",Fiji (859 178)
27,27,Roraima,652 713,"0,3%",Luxemburgo (562 958)

## Desafio: Limpar os dados do excel (Sem regiões) com nomes de colunas apropriados

In [97]:
ibge_estimativa_git = ibge_estimativa_git.drop(columns="Unnamed: 1").head()
ibge_estimativa_git.head()

,ESTIMATIVAS DA POPULAÇÃO RESIDENTE NO BRASIL E UNIDADES DA FEDERAÇÃO COM DATA DE REFERÊNCIA EM 1º DE JULHO DE 2020,Unnamed: 2
0,BRASIL E UNIDADES DA FEDERAÇÃO,POPULAÇÃO ESTIMADA
1,Brasil,211755692
2,Região Norte,18672591
3,Rondônia,1796460
4,Acre,894470

## 1ª Forma de renomear as colunas

In [98]:
ibge_estimativa_git = ibge_estimativa_git.rename(columns={"ESTIMATIVAS DA POPULAÇÃO RESIDENTE NO BRASIL E UNIDADES DA FEDERAÇÃO COM DATA DE REFERÊNCIA EM 1º DE JULHO DE 2020": "Unidade da Federação",
                                    "Unnamed: 2": "População Estimada"})
ibge_estimativa_git.head()

             Unidade da Federação  População Estimada
0  BRASIL E UNIDADES DA FEDERAÇÃO  POPULAÇÃO ESTIMADA
1                          Brasil           211755692
2                    Região Norte            18672591
3                        Rondônia             1796460
4                            Acre              894470

## 2ª Fomra de renomear as colunas

In [99]:
ibge_estimativa_git = pd.read_excel(r"https://github.com/alura-cursos/agendamento-hospitalar/blob/main/dados/estimativa_dou_2020.xls?raw=true")
ibge_estimativa_git.head()

,ESTIMATIVAS DA POPULAÇÃO RESIDENTE NO BRASIL E UNIDADES DA FEDERAÇÃO COM DATA DE REFERÊNCIA EM 1º DE JULHO DE 2020,Unnamed: 1,Unnamed: 2
0,BRASIL E UNIDADES DA FEDERAÇÃO,NaN,POPULAÇÃO ESTIMADA
1,Brasil,NaN,211755692
2,Região Norte,NaN,18672591
3,Rondônia,NaN,1796460
4,Acre,NaN,894470

In [100]:
ibge_estimativa_git.columns = ["uf", "populacao", "pais_comparavel" ]
ibge_estimativa_git.head()

                               uf  populacao     pais_comparavel
0  BRASIL E UNIDADES DA FEDERAÇÃO        NaN  POPULAÇÃO ESTIMADA
1                          Brasil        NaN           211755692
2                    Região Norte        NaN            18672591
3                        Rondônia        NaN             1796460
4                            Acre        NaN              894470

In [101]:
ibge_estimativa_git = ibge_estimativa_git.drop(index=0)
ibge_estimativa_git.head()

             uf  populacao pais_comparavel
1        Brasil        NaN       211755692
2  Região Norte        NaN        18672591
3      Rondônia        NaN         1796460
4          Acre        NaN          894470
5      Amazonas        NaN         4207714

In [102]:
ibge_estimativa_git = ibge_estimativa_git.drop(columns="populacao").head()
ibge_estimativa_git.head()

             uf pais_comparavel
1        Brasil       211755692
2  Região Norte        18672591
3      Rondônia         1796460
4          Acre          894470
5      Amazonas         4207714

## Ler dados da Wikipedia com read_html

In [103]:
dados_wikipedia = pd.read_html("https://pt.wikipedia.org/wiki/Lista_de_unidades_federativas_do_Brasil_por_popula%C3%A7%C3%A3o#cite_note-IBGE_POP-1", skiprows=1)

In [104]:
dados_wikipedia

[     Unidade federativa  2024 (est.)         2022       %        Abs.  \
               São Paulo   45 973 194   44 411 238   7,63%   3 149 039
 0          Minas Gerais   21 322 691   20 539 989   4,81%     942 659
 1        Rio de Janeiro   17 219 679   16 055 174   0,41%      65 245
 2                 Bahia   14 850 513   14 141 626   0,89%     124 720
 3                Paraná   11 824 665   11 444 380   9,57%     999 854
 4     Rio Grande do Sul   11 229 915   10 882 965   1,77%     189 036
 5            Pernambuco    9 539 029    9 058 931   2,98%     262 483
 6                 Ceará    9 233 656    8 794 957   4,05%     342 576
 7                  Pará    8 664 306    8 120 131   7,11%     539 080
 8        Santa Catarina    8 058 441    7 610 361  21,80%   1 361 925
 9                 Goiás    7 350 483    7 056 495  17,53%   1 052 707
 10             Maranhão    7 010 960    6 776 699   3,07%     201 910
 11             Amazonas    4 281 209    3 941 613  13,14%     457 628
 12              Paraíba    4 145 040    3 974 687   5,53%     208 159
 13       Espírito Santo    4 102 129    3 833 712   9,07%     318 760
 14          Mato Grosso    3 836 399    3 658 649  20,54%     623 527
 15  Rio Grande do Norte    3 446 071    3 302 729   4,25%     134 702
 16                Piauí    3 375 646    3 271 199   4,90%     152 839
 17              Alagoas    3 220 104    3 127 683   0,23%       7 189
 18     Distrito Federal    2 982 818    2 817 381   9,62%     247 221
 19   Mato Grosso do Sul    2 901 895    2 757 013  12,58%     307 989
 20              Sergipe    2 291 077    2 210 004   6,87%     141 987
 21             Rondônia    1 746 227    1 581 196   1,20%      18 787
 22            Tocantins    1 577 342    1 511 460   9,25%     128 015
 23                 Acre      880 631      830 018  13,15%      96 459
 24                Amapá      802 837      733 759   9,59%      64 233
 25              Roraima      716 793      636 707  41,34%     186 228
 26                Total  212 583 750  203 080 756   6,46%  12 324 957

    % do total (2024)[4] País comparável (habitantes)[5][a]
                  21,63%                Iraque (46 042 015)
 0                10,03%                Zâmbia (21 314 956)
 1                 8,10%               Camboja (17 638 801)
 2                 6,99%                 Guiné (14 754 785)
 3                 5,56%                 Haiti (11 772 557)
 4                 5,28%  República Dominicana (11 427 557)
 5                 4,49%                   Togo (9 515 236)
 6                 4,34%                Áustria (9 120 813)
 7                 4,08%             Serra Leoa (8 642 022)
 8                 3,79%                   Laos (7 769 819)
 9                 3,46%                  Líbia (7 381 023)
 10                3,30%               Paraguai (6 929 153)
 11                2,01%                 Panamá (4 515 577)
 12                1,95%                Croácia (3 875 325)
 13                1,93%                Croácia (3 875 325)
 14                1,80%                Geórgia (3 807 670)
 15                1,62%               Mongólia (3 475 540)
 16                1,59%                Uruguai (3 386 588)
 17                1,51%   Bósnia e Herzegovina (3 164 253)
 18                1,40%                Armênia (2 973 840)
 19                1,37%               Lituânia (2 859 110)
 20                1,08%                 Lesoto (2 337 423)
 21                0,82%     Macedônia do Norte (1 823 009)
 22                0,74%                Bahrein (1 607 049)
 23                0,41%                  Comores (866 628)
 24                0,38%                    Butão (791 524)
 25                0,34%               Luxemburgo (673 036)
 26                 100%                                  —  ,
          Região  2024 (est.)         2022       %        Abs.  \
         Sudeste   88 617 693   84 840 113   5,57%   4 475 703
 0      Nordeste   57 112 096   54 658 515   2,97%   1 576 565
 1           Sul   31 113 021   29 937 706   9,31%   2 550 815
 2         Norte   18 669 345   17 354 884   9,39%   1 490 430
 3  Centro-Oeste   17 071 595   16 289 538  15,87%   2 231 444
 4         Total  212 583 750  203 080 756   6,46%  12 324 957

   % do total (2024)[4] País comparável (habitantes)[5][a]
                 41,69%               Turquia (87 473 805)
 0               26,87%                Quênia (56 432 944)
 1               14,64%       Costa do Marfim (31 934 230)
 2                8,78%               Senegal (18 501 984)
 3                8,03%              Zimbabwe (16 634 373)
 4                 100%                                  —  ,
                            Geografia  \
 0                         Demografia
 1                            Governo
 2  Indicadores econômicos  e sociais
 3                           Educação
 4                           Economia
 5                              Saúde
 6                            Sociais
 7                           Trabalho
 8                             Outros

   Área Densidade demográfica Número de municípios por estado Urbanização Município mais alto por estado Ponto culminante
 0  População Densidade demográfica Natalidade Fec...
 1  Sedes governamentais Transparência Arrecadação...
 2  Educação Alfabetização Crianças e adolescentes...
 3  Alfabetização Crianças e adolescentes fora da ...
 4  Crescimento Crescimento nominal Participação P...
 5  Mortalidade infantil Óbitos infantis Taxa de h...
 6  GINI IDH segundo cor/raça IFDM Incidência da p...
 7  Empregados com carteira assinada Desemprego Ap...
 8  Automóveis per capita Celulares por habitante ...                                                                      ,
           0                                                  1
 0  Economia  Crescimento Crescimento nominal Participação P...
 1     Saúde  Mortalidade infantil Óbitos infantis Taxa de h...
 2   Sociais  GINI IDH segundo cor/raça IFDM Incidência da p...
 3  Trabalho  Empregados com carteira assinada Desemprego Ap...
 4    Outros  Automóveis per capita Celulares por habitante ...]

## Ajustando espaços em branco

In [108]:
dados_da_populacao_io.columns = ["posicao", "uf", "populacao", "porcentagem", "pais_comparavel"]
dados_da_populacao_io.head()

,posicao,uf,populacao,porcentagem,pais_comparavel
1,1,São Paulo,46 649 132,"21,9%",Flag of Spain.svg Espanha (46 439 864)
2,2,Minas Gerais,21 411 923,"10,1%",Sri Lanka (20 675 000)
3,3,Rio de Janeiro,17 463 349,"8,2%",Países Baixos (16 922 900)
4,4,Bahia Bahia,14 985 284,"7,1%",Chade (14 037 000)
5,5,Paraná,11 597 484,"5,4%",Bolívia (11 410 651)

In [113]:
dados_da_populacao_io["populacao"] = dados_da_populacao_io["populacao"].str.replace(' ', '').astype(int)
dados_da_populacao_io.head()

C:\Users\Lucas Lira\AppData\Local\Temp\ipykernel_13016\2816833581.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_da_populacao_io["populacao"] = dados_da_populacao_io["populacao"].str.replace(' ', '').astype(int)

,posicao,uf,populacao,porcentagem,pais_comparavel
1,1,São Paulo,46649132,"21,9%",Flag of Spain.svg Espanha (46 439 864)
2,2,Minas Gerais,21411923,"10,1%",Sri Lanka (20 675 000)
3,3,Rio de Janeiro,17463349,"8,2%",Países Baixos (16 922 900)
4,4,Bahia Bahia,14985284,"7,1%",Chade (14 037 000)
5,5,Paraná,11597484,"5,4%",Bolívia (11 410 651)

## Verificando tipagem de cada coluna

In [114]:
dados_da_populacao_io.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 1 to 27
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   posicao          27 non-null     object
 1   uf               27 non-null     object
 2   populacao        27 non-null     int64
 3   porcentagem      27 non-null     object
 4   pais_comparavel  27 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.3+ KB

## 2. Proporcionalidade e Seaborn